server:
  port: 8000

spring:
  application:
    name: microservicecloud-producer 
      
# circuit breaker in feign client
feign: 
  hystrix: 
    enabled: true


# configure eureka regisration centre
eureka:
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      
#logs      
logging:
  level:
    com:
      example:
        demo:
          service:
            UserService: debug      