server: 
  port: 7002
 
eureka: 
  instance:
    hostname: eureka7002.com #eureka instance id 
    appname: eureka-cluster
  client: 
    register-with-eureka: true     #false表示不向注册中心注册自己。
    fetch-registry: true     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       
      defaultZone: http://eureka7001.com:7001/eureka/ #Eureka Server interaction's dependency address 